## default connection pool
server:
  port: 8080
debug: true
spring:
  #config:
   # import: env.properties
  sql:
    init:
      platform: mongodb
      mode: always
  output:
    ansi:
      enabled: always

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}
      database: ${MONGO_DATABASE}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR